=== hekai7217/java_code/java_xml/src/com/jutixueyuan/dtd/student.dtd
<!ELEMENT students (student*) >
<!--
    ELEMENT 元素   元素标签 students  可以有多个 student 标签
 -->
<!ELEMENT student (name,age,sex)>
<!--
        ELEMENT 元素   元素标签 student 可以哟 标签 name,age,sex, 顺序也不能错误
-->
<!ELEMENT name (#PCDATA)>
<!-- 元素 name 标签  中可以写文本 -->
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST student number CDATA #REQUIRED>
<!-- 多个student标签 必须有number 属性  -->

<!--上面就是 dtd 的约束规则-->

=== hekai7217/java_code/java_xml/src/com/jutixueyuan/dtd/student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "C:\java_lesson\java_10_9\java_code\java_xml\src\com\jutixueyuan\dtd\student.dtd">
<!--  xml 文件中 引入  dtd 约束文件 -->
<!--
 dtd 的约束 数据不够完整
    有一个更加强大的 xsd 约束 可以 约束数据类型 和命名空间
-->
<students>

	<student number="001">
		<name>张翠山</name>
		<age>1000</age>
		<sex>李</sex>
	</student>

	<student number="002">
		<name>殷素素</name>
		<age>28</age>
		<sex>女</sex>
	</student>

</students>
