=== hekai7217/java_code/java_xml/src/com/jutixueyuan/xsd/student.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="http://www.szsxt.cn/xml"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.szsxt.cn/xml" elementFormDefault="qualified">
<!--
       xmlns="http://www.szsxt.cn/xml"  定义命名空间
       xmlns:xsd="http://www.w3.org/2001/XMLSchema"  xsd的协议规定
       targetNamespace="http://www.szsxt.cn/xml"  当前命名空间名称
-->
<!--
    定义了 students 标签元素   元素类型 studentsType
-->
    <xsd:element name="students" type="studentsType"/>
<!--
   studentsType 定义了 studentsType 类性
    studentsType 有 可以有student元素
    student 的 元素类型是  studentType
-->
    <xsd:complexType name="studentsType">
        <xsd:sequence>
            <xsd:element name="student" type="studentType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
<!--    定义了 student 类型
           student 标签可以 number 属性   有 name / age  /sex 元素
           number 属性   自定义numberType 类型     字符 + 正则  (sxt_4个数字)
           name  数据类型  string
           age   ageType 是自定义类型     integer 类型 有范围(0 - 100)
           sex   sexType 是自定义类型      字符串枚举类型  (male/ female)
-->
    <xsd:complexType name="studentType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="age" type="ageType" />
            <xsd:element name="sex" type="sexType" />
        </xsd:sequence>
        <xsd:attribute name="number" type="numberType" use="required"/>
    </xsd:complexType>
    <xsd:simpleType name="sexType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="male"/>
            <xsd:enumeration value="female"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="ageType">
        <xsd:restriction base="xsd:integer">
        <xsd:minInclusive value="0"/>
        <xsd:maxInclusive value="100"/>
    </xsd:restriction>
    </xsd:simpleType>

<!--  student的  number 的自定类型
          字符 + 正则  (sxt_4个数字)
    -->
    <xsd:simpleType name="numberType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="sxt_\d{4}"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== hekai7217/java_code/java_xml/src/com/jutixueyuan/xsd/studenta.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
	1.填写xml文档的根元素
	2.引入xsi前缀.  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	3.引入xsd文件命名空间.  xsi:schemaLocation="http://www.sxsxt.cn/xml student.xsd"
	4.为每一个xsd约束声明一个前缀,作为标识  xmlns="http://www.szsxt.cn/xml"
	xmlns:a 设置前缀 每个标签都需要加前缀 (设置前缀为了区分 相同标签)
	xmlns 默认 前面不用加   
 -->
 <stu:students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 		   xsi:schemaLocation="http://www.szsxt.cn/xml student.xsd"
 		   xmlns:stu="http://www.szsxt.cn/xml"
 		    >

	<stu:student number="sxt_0001">
		<stu:name>杨逍</stu:name>
		<stu:age>30</stu:age>
		<stu:sex>male</stu:sex>
	</stu:student>

	<stu:student number="sxt_0002">
		<stu:name>范瑶</stu:name>
		<stu:age>28</stu:age>
		<stu:sex>male</stu:sex>
	</stu:student>

 </stu:students>
